# Header
menu:
  主页: /

# Content
excerpt_link: 更多
prev: 上一个
next: 下一个
reply: 回复
share: 分享
fancybox: true

# Sidebar
widgets:
- search
- music
- category
- recent_posts
- tag
- tagcloud

# Miscellaneous
google_analytics: UA-141035963-1
duoshuo_shortname: 
rss: 
google_site_verification: 
baidu_site_verification: 
favicon: https://img.vim-cn.com/ff/e03714b63e99190d51ae1126bf2181d7bf3358.bmp
music: 